### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by exalted**
/cc: @as-cii

### CODE REVIEW

**Comment by as-cii** [comment]
@exalted: why did you specify a PhantomJs version?

**Comment by exalted** [comment]
Because, it doesn't work with the latest version, that is `2.x`, hence the `README`. 

Ali




On Tue, Mar 24, 2015 at 10:49 AM -0700, "Antonio Scandurra" <notifications@github.com> wrote:












@exalted: why did you specify a PhantomJs version?

**Comment by as-cii** [comment]
@exalted: makes sense. However,  before merging this, I'd like to investigate whether or not we could update to the latest version. We may still want to specify a version constraint in our README, but let's do a bit of research first.

I'll report here what I find out :eyeglasses:

**Comment by as-cii** [comment]
After reading http://phantomjs.org/release-2.0.html, I decided to bump our poltergeist version to support the latest phantomjs.

CI is :green_heart: on #53 :+1:  What do you think if we update this README to simply link to the latest version of `phantomjs` (namely `brew install phantomjs`)?

Thanks.

**Comment by exalted** [comment]
Agreed!


Ali

On Wed, Mar 25, 2015 at 8:37 AM, Antonio Scandurra <notifications@github.com

**Pull request merged**
