### PR TITLE
Add card description to e-mail notification (if there’s one)

### PR DESCRIPTION
**Pull request by as-cii**
--
[Open card on Catchup](http://catchup.io/boards/3/cards/180)

### CODE REVIEW

**Comment by exalted** [comment]
I am not sure how good is it to render markdown in e-mail like that. Since styles are going to be missing, I am not sure if it looks okay.

How about using one of the default renderers included in Redcarpet instead?

**Comment by as-cii** [comment]
This is how we do it for comments, and I did likewise here for the sake of consistency.

It might not be the *best* solution, but it has worked well so far for comments and I'd stick with it once we want to change both of them.

Thoughts? :thought_balloon:

**Comment by exalted** [comment]
I know, I know. Let’s change both of them? :grinning:

**Comment by exalted** [comment]
I mean, I don’t know. I don’t wanna be a PITA. So whatever you feel like to.

**Comment by as-cii** [comment]
@exalted: please, merge this if you're fine with the latest changes :smile:

**Comment by exalted** [comment]
@as-cii could you send me an example notification? :wink:

**Comment by as-cii** [comment]
@exalted: no, not really. While previewing the application, we set `RAILS_ENV` to `development` and therefore e-mails won't be delivered. I can hack it, though, and set `RAILS_ENV` to `production` just for the sake of trying this out. I'll ping you on Slack as soon as I do that.

This `RAILS_ENV` thing has hit us several times and I am more and more convinced we should keep the environment to `production` and have a separate variable instead (to understand which environment we're in). Still unsure about this, though... Maybe we should gather more evidence from other users?

**Comment by exalted** [comment]
:+1: let’s hold it for a little more.

**Pull request merged**
